# Learning Python

There are lots of great online resources for learning Python and learning Jupyter notebooks with Python.    

### Probably the best, most complete book on scientific Python:

A Primer on Scientific Programming with Python (Texts in Computational Science and Engineering) 5th ed. 2016 Edition

by Hans Petter Langtangen

https://www.amazon.com/Scientific-Programming-Computational-Science-Engineering/dp/3662498863/ref=mt_hardcover?_encoding=UTF8

#### Experts and intermediates - Patience please!!!

Let's start with some simple introduction.

Printing text in python is very easy.

In [1]:
print 'Hello World!'

Hello World!


In [2]:
print 1

1


What's the difference between '1' and 1?

Let's try.

In [3]:
print '1'

1


In [4]:
print 1

1


Let's try and assign values to variables.

In [5]:
a = 10      # I assign the value of a to 1.

In [6]:
print a

10


In [7]:
type(a)    # What is the type of a? Is it an integer or a floating point number or a string...?

int

In [8]:
a = 'Batman'

In [9]:
print a

Batman


In [10]:
type(a)

str

In [11]:
b = a    # Set b equals to a. Now b assigns the value of a.

In [12]:
b

'Batman'

In [13]:
a = 15.75

In [14]:
a

15.75

In [15]:
b

'Batman'

In [16]:
type(a)

float

### Introduction to If-else (conditional statements)

In [17]:
if a < 16.0:
    print "less than sweet 16!"
else:
    print "more than sweet 16!"    # More than or equal-to in reality!

less than sweet 16!


### Loops (for loop)

In [18]:
for i in range(0,10):
    print i

0
1
2
3
4
5
6
7
8
9


In [19]:
import random
circle = 0
square = 100
for i in range(square):
    x,y = random.randrange(0,100000),random.randrange(0,100000)
    if ((x**2)+(y**2)) < 10000000000:
        circle += 1
print float(circle)/float(square)

0.78


In [20]:
import math
math.pi/4.0    # Check the value with what we obtained using MC

0.7853981633974483

### Arrays:

In [21]:
a = [1,3,7]   # An 1-d array

In [22]:
a

[1, 3, 7]

In [23]:
a[1]

3

In [24]:
a[0]

1

In [25]:
a[0] = 'new'

In [26]:
a

['new', 3, 7]

In [27]:
a.append(3.5)

In [28]:
a

['new', 3, 7, 3.5]

In [29]:
type(a)

list

In [30]:
a = 4.5

In [31]:
print a

4.5


### Let's move on to 2D arrays. 1D is boring! 

In [32]:
my_array = [[]]

In [33]:
print my_array

[[]]


In [34]:
my_array.append(3.5)

In [35]:
my_array

[[], 3.5]

In [36]:
my_array = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [37]:
my_array

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [38]:
import numpy as np
np.matrix(my_array)

matrix([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [39]:
import pandas as pd
pd.DataFrame(my_array, columns=list('012'))

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0

### Let's solve a real problem now!

We need to find the distance between all atoms in a given molecule.

Test case: Benzene - http://cccbdb.nist.gov

In [40]:
!cat files/benzene.xyz

12

C1    0.0000    1.3862    0.0000
C2    1.2005    0.6931    0.0000
C3    1.2005    -0.6931    0.0000
C4    0.0000    -1.3862    0.0000
C5    -1.2005    -0.6931    0.0000
C6    -1.2005    0.6931    0.0000
H7    0.0000    2.4617    0.0000
H8    2.1319    1.2309    0.0000
H9    2.1319    -1.2309    0.0000
H10    0.0000    -2.4617    0.0000
H11    -2.1319    -1.2309    0.0000
H12    -2.1319    1.2309    0.0000


In [41]:
import parse_xyz
atoms = parse_xyz.parse_atoms()
coordinates = parse_xyz.parse_coordinates()

In [42]:
coordinates

[array([ 0.    ,  1.3862,  0.    ]),
 array([ 1.2005,  0.6931,  0.    ]),
 array([ 1.2005, -0.6931,  0.    ]),
 array([ 0.    , -1.3862,  0.    ]),
 array([-1.2005, -0.6931,  0.    ]),
 array([-1.2005,  0.6931,  0.    ]),
 array([ 0.    ,  2.4617,  0.    ]),
 array([ 2.1319,  1.2309,  0.    ]),
 array([ 2.1319, -1.2309,  0.    ]),
 array([ 0.    , -2.4617,  0.    ]),
 array([-2.1319, -1.2309,  0.    ]),
 array([-2.1319,  1.2309,  0.    ])]

In [43]:
atoms

['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'H7', 'H8', 'H9', 'H10', 'H11', 'H12']

In [44]:
!cat parse_xyz.py

import re, numpy

def parse_atoms():
	inputFile=open('files/benzene.xyz','r')
	a = inputFile.read()
	a = a.split('\n')
	atoms = ['atomname']*12
	coordinates = [[0.0 for x in range(3)] for y in range(12)]
	for i in range(len(a)):
		a[i] = re.sub(' +',' ',a[i])
		a[i] = a[i].rstrip()
		a[i] = a[i].split(' ')
	for i in range(2,14):
		atoms[i-2] = a[i][0]
	return atoms

def parse_coordinates():
	inputFile=open('files/benzene.xyz','r')
	a = inputFile.read()
	a = a.split('\n')
	atoms = ['atomname']*12
	coordinates = [[0.0 for x in range(3)] for y in range(12)]
	for i in range(len(a)):
		a[i] = re.sub(' +',' ',a[i])
		a[i] = a[i].rstrip()
		a[i] = a[i].split(' ')
	for i in range(2,14):
		coordinates[i-2] = numpy.array((float(a[i][1]),float(a[i][2]),float(a[i][3])))
	return coordinates


In [45]:
import pandas as pd
pd.DataFrame(coordinates, columns=list('xyz'))

x       y    z
0   0.0000  1.3862  0.0
1   1.2005  0.6931  0.0
2   1.2005 -0.6931  0.0
3   0.0000 -1.3862  0.0
4  -1.2005 -0.6931  0.0
5  -1.2005  0.6931  0.0
6   0.0000  2.4617  0.0
7   2.1319  1.2309  0.0
8   2.1319 -1.2309  0.0
9   0.0000 -2.4617  0.0
10 -2.1319 -1.2309  0.0
11 -2.1319  1.2309  0.0

In [46]:
coordinates[1]

array([ 1.2005,  0.6931,  0.    ])

In [47]:
import math
distance = [[5.0 for x in range(12)]for y in range(12)]
for i in range(len(coordinates)):
    for j in range(len(coordinates)):
        distance[i][j] = math.sqrt(((coordinates[i][0]-coordinates[j][0])**2)+((coordinates[i][1]-coordinates[j][1])**2)+((coordinates[i][2]-coordinates[j][2])**2))

In [48]:
distance

[[0.0,
  1.3862134972651219,
  2.400976622126921,
  2.7724,
  2.400976622126921,
  1.3862134972651219,
  1.0755,
  2.1375489935905563,
  3.3755310722906993,
  3.8479,
  3.3755310722906993,
  2.1375489935905563],
 [1.3862134972651219,
  0.0,
  1.3862,
  2.400976622126921,
  2.7724269945302438,
  2.401,
  2.137556130257168,
  1.075516062176665,
  2.137587883573445,
  3.3754945252510775,
  3.8479430557117134,
  3.375517530690664],
 [2.400976622126921,
  1.3862,
  0.0,
  1.3862134972651219,
  2.401,
  2.7724269945302438,
  3.3754945252510775,
  2.137587883573445,
  1.075516062176665,
  2.137556130257168,
  3.375517530690664,
  3.8479430557117134],
 [2.7724,
  2.400976622126921,
  1.3862134972651219,
  0.0,
  1.3862134972651219,
  2.400976622126921,
  3.8479,
  3.3755310722906993,
  2.1375489935905563,
  1.0755,
  2.1375489935905563,
  3.3755310722906993],
 [2.400976622126921,
  2.7724269945302438,
  2.401,
  1.3862134972651219,
  0.0,
  1.3862,
  3.3754945252510775,
  3.8479430557117134,
 

In [49]:
import pandas as pd
pd.DataFrame(distance)

0         1         2         3         4         5         6   \
0   0.000000  1.386213  2.400977  2.772400  2.400977  1.386213  1.075500   
1   1.386213  0.000000  1.386200  2.400977  2.772427  2.401000  2.137556   
2   2.400977  1.386200  0.000000  1.386213  2.401000  2.772427  3.375495   
3   2.772400  2.400977  1.386213  0.000000  1.386213  2.400977  3.847900   
4   2.400977  2.772427  2.401000  1.386213  0.000000  1.386200  3.375495   
5   1.386213  2.401000  2.772427  2.400977  1.386200  0.000000  2.137556   
6   1.075500  2.137556  3.375495  3.847900  3.375495  2.137556  0.000000   
7   2.137549  1.075516  2.137588  3.375531  3.847943  3.375518  2.461680   
8   3.375531  2.137588  1.075516  2.137549  3.375518  3.847943  4.263835   
9   3.847900  3.375495  2.137556  1.075500  2.137556  3.375495  4.923400   
10  3.375531  3.847943  3.375518  2.137549  1.075516  2.137588  4.263835   
11  2.137549  3.375518  3.847943  3.375531  2.137588  1.075516  2.461680   

          7         8         9         10        11  
0   2.137549  3.375531  3.847900  3.375531  2.137549  
1   1.075516  2.137588  3.375495  3.847943  3.375518  
2   2.137588  1.075516  2.137556  3.375518  3.847943  
3   3.375531  2.137549  1.075500  2.137549  3.375531  
4   3.847943  3.375518  2.137556  1.075516  2.137588  
5   3.375518  3.847943  3.375495  2.137588  1.075516  
6   2.461680  4.263835  4.923400  4.263835  2.461680  
7   0.000000  2.461800  4.263835  4.923459  4.263800  
8   2.461800  0.000000  2.461680  4.263800  4.923459  
9   4.263835  2.461680  0.000000  2.461680  4.263835  
10  4.923459  4.263800  2.461680  0.000000  2.461800  
11  4.263800  4.923459  4.263835  2.461800  0.000000

# Can we make it more EFFICIENT?

In [50]:
import math
dist_mat = [[5.0 for x in range(12)]for y in range(12)]
for i in range(len(coordinates)):
    for j in range(i, len(coordinates)):
        dist_mat[i][j] = math.sqrt(((coordinates[i][0]-coordinates[j][0])**2)+((coordinates[i][1]-coordinates[j][1])**2)+((coordinates[i][2]-coordinates[j][2])**2))
        dist_mat[j][i] = dist_mat[i][j]

In [51]:
import pandas as pd
pd.DataFrame(dist_mat)

0         1         2         3         4         5         6   \
0   0.000000  1.386213  2.400977  2.772400  2.400977  1.386213  1.075500   
1   1.386213  0.000000  1.386200  2.400977  2.772427  2.401000  2.137556   
2   2.400977  1.386200  0.000000  1.386213  2.401000  2.772427  3.375495   
3   2.772400  2.400977  1.386213  0.000000  1.386213  2.400977  3.847900   
4   2.400977  2.772427  2.401000  1.386213  0.000000  1.386200  3.375495   
5   1.386213  2.401000  2.772427  2.400977  1.386200  0.000000  2.137556   
6   1.075500  2.137556  3.375495  3.847900  3.375495  2.137556  0.000000   
7   2.137549  1.075516  2.137588  3.375531  3.847943  3.375518  2.461680   
8   3.375531  2.137588  1.075516  2.137549  3.375518  3.847943  4.263835   
9   3.847900  3.375495  2.137556  1.075500  2.137556  3.375495  4.923400   
10  3.375531  3.847943  3.375518  2.137549  1.075516  2.137588  4.263835   
11  2.137549  3.375518  3.847943  3.375531  2.137588  1.075516  2.461680   

          7         8         9         10        11  
0   2.137549  3.375531  3.847900  3.375531  2.137549  
1   1.075516  2.137588  3.375495  3.847943  3.375518  
2   2.137588  1.075516  2.137556  3.375518  3.847943  
3   3.375531  2.137549  1.075500  2.137549  3.375531  
4   3.847943  3.375518  2.137556  1.075516  2.137588  
5   3.375518  3.847943  3.375495  2.137588  1.075516  
6   2.461680  4.263835  4.923400  4.263835  2.461680  
7   0.000000  2.461800  4.263835  4.923459  4.263800  
8   2.461800  0.000000  2.461680  4.263800  4.923459  
9   4.263835  2.461680  0.000000  2.461680  4.263835  
10  4.923459  4.263800  2.461680  0.000000  2.461800  
11  4.263800  4.923459  4.263835  2.461800  0.000000

# Can we make it EVEN more EFFICIENT?

In [52]:
import math,numpy
dist_mat2 = [[5.0 for x in range(12)]for y in range(12)]
for i in range(len(coordinates)):
    for j in range(i, len(coordinates)):
        dist_mat2[i][j] = numpy.linalg.norm(coordinates[i]-coordinates[j])
        dist_mat2[j][i] = dist_mat2[i][j]

In [53]:
import pandas as pd
pd.DataFrame(dist_mat2)

0         1         2         3         4         5         6   \
0   0.000000  1.386213  2.400977  2.772400  2.400977  1.386213  1.075500   
1   1.386213  0.000000  1.386200  2.400977  2.772427  2.401000  2.137556   
2   2.400977  1.386200  0.000000  1.386213  2.401000  2.772427  3.375495   
3   2.772400  2.400977  1.386213  0.000000  1.386213  2.400977  3.847900   
4   2.400977  2.772427  2.401000  1.386213  0.000000  1.386200  3.375495   
5   1.386213  2.401000  2.772427  2.400977  1.386200  0.000000  2.137556   
6   1.075500  2.137556  3.375495  3.847900  3.375495  2.137556  0.000000   
7   2.137549  1.075516  2.137588  3.375531  3.847943  3.375518  2.461680   
8   3.375531  2.137588  1.075516  2.137549  3.375518  3.847943  4.263835   
9   3.847900  3.375495  2.137556  1.075500  2.137556  3.375495  4.923400   
10  3.375531  3.847943  3.375518  2.137549  1.075516  2.137588  4.263835   
11  2.137549  3.375518  3.847943  3.375531  2.137588  1.075516  2.461680   

          7         8         9         10        11  
0   2.137549  3.375531  3.847900  3.375531  2.137549  
1   1.075516  2.137588  3.375495  3.847943  3.375518  
2   2.137588  1.075516  2.137556  3.375518  3.847943  
3   3.375531  2.137549  1.075500  2.137549  3.375531  
4   3.847943  3.375518  2.137556  1.075516  2.137588  
5   3.375518  3.847943  3.375495  2.137588  1.075516  
6   2.461680  4.263835  4.923400  4.263835  2.461680  
7   0.000000  2.461800  4.263835  4.923459  4.263800  
8   2.461800  0.000000  2.461680  4.263800  4.923459  
9   4.263835  2.461680  0.000000  2.461680  4.263835  
10  4.923459  4.263800  2.461680  0.000000  2.461800  
11  4.263800  4.923459  4.263835  2.461800  0.000000

# Is there any still ANY room for improvement?

In [54]:
import math,numpy
dist_mat3 = [[5.0 for x in range(12)]for y in range(12)]
for i in range(len(coordinates)):
    for j in range(i+1, len(coordinates)):
        dist_mat3[i][j] = numpy.linalg.norm(coordinates[i]-coordinates[j])
        dist_mat3[j][i] = dist_mat3[i][j]

In [55]:
import pandas as pd
pd.DataFrame(dist_mat3)

0         1         2         3         4         5         6   \
0   5.000000  1.386213  2.400977  2.772400  2.400977  1.386213  1.075500   
1   1.386213  5.000000  1.386200  2.400977  2.772427  2.401000  2.137556   
2   2.400977  1.386200  5.000000  1.386213  2.401000  2.772427  3.375495   
3   2.772400  2.400977  1.386213  5.000000  1.386213  2.400977  3.847900   
4   2.400977  2.772427  2.401000  1.386213  5.000000  1.386200  3.375495   
5   1.386213  2.401000  2.772427  2.400977  1.386200  5.000000  2.137556   
6   1.075500  2.137556  3.375495  3.847900  3.375495  2.137556  5.000000   
7   2.137549  1.075516  2.137588  3.375531  3.847943  3.375518  2.461680   
8   3.375531  2.137588  1.075516  2.137549  3.375518  3.847943  4.263835   
9   3.847900  3.375495  2.137556  1.075500  2.137556  3.375495  4.923400   
10  3.375531  3.847943  3.375518  2.137549  1.075516  2.137588  4.263835   
11  2.137549  3.375518  3.847943  3.375531  2.137588  1.075516  2.461680   

          7         8         9         10        11  
0   2.137549  3.375531  3.847900  3.375531  2.137549  
1   1.075516  2.137588  3.375495  3.847943  3.375518  
2   2.137588  1.075516  2.137556  3.375518  3.847943  
3   3.375531  2.137549  1.075500  2.137549  3.375531  
4   3.847943  3.375518  2.137556  1.075516  2.137588  
5   3.375518  3.847943  3.375495  2.137588  1.075516  
6   2.461680  4.263835  4.923400  4.263835  2.461680  
7   5.000000  2.461800  4.263835  4.923459  4.263800  
8   2.461800  5.000000  2.461680  4.263800  4.923459  
9   4.263835  2.461680  5.000000  2.461680  4.263835  
10  4.923459  4.263800  2.461680  5.000000  2.461800  
11  4.263800  4.923459  4.263835  2.461800  5.000000

## One last thing: Eigenvalue problem.

In [56]:
import numpy
my_matrix = numpy.array(([[2.0, 7.0], [-1.0, -6.0]]))

# Note: I am using Float, even though the numbers here are ints!!!


# How to compute the eigenvalue and eigenvectors corresponding to this matrix?






































my_matrix

array([[ 2.,  7.],
       [-1., -6.]])

In [57]:
eigenval, eigenvec = numpy.linalg.eig(my_matrix)

In [58]:
eigenval

array([ 1., -5.])

In [59]:
eigenvec

array([[ 0.98994949, -0.70710678],
       [-0.14142136,  0.70710678]])

# Moral: Do not try to reinvent the wheel.

<img src="https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAZSAAAAJDRlMWFlMzAyLWIyZmItNDY3ZS04ZjM0LTAzYTA0MTI4MmViMw.png" width=800>